### ISSUE TITLE
Could it be applied in single cell RNAseq data?

### ISSUE THREAD

**Issue by x811zou** [biosinodx/SCcaller#4]
I have a single cell RNAseq data from 10X genomics, along with the reference.
Could I use SCcaller to identify variants from my sample?

**Comment by x811zou** [comment]
Also, I am wondering what is the difference between SCcaller and Monovar? In terms of usage, I noticed that Monovar can take a list of BAM files, while SCcaller can only take one BAM file.

**Comment by biosinodx** [comment]
This is an interesting question. I think SCcaller can produce results on RNA seq data from 10x (although I never tested it). However, the experiment (amplification) may produce a lot of artifactual variants. This should be carefully tested.

About SCcaller and Monovar, they are developed for almost the same purpose. They are different in performance. About input and output, they are different, but this does not seem to be a major thing.

**Comment by x811zou** [comment]
@biosinodx Thank you very much for your reply!
Just one more question, does the output VCF file from SCcaller has 'contig' information in the header? 
I am asking this question is because I do not see a small tutorial dataset here, and my sample is quite big. I'd like to know what would I expect to get from the output.

**Comment by biosinodx** [comment]
SCcaller does not output VCF file. It will output a bed file. I'm considering to switch to VCF in the future :)

**Comment by biosinodx** [comment]
Hi, sccaller cannot be applied to single-cell RNA seq data.
