### ISSUE TITLE
Did you mean v1.21 or v1.2.1

### ISSUE THREAD

**Issue by epruesse** [biosinodx/SCcaller#5]
The latest release increased the minor version from 2 to 21. Was this intentional? Please be aware that 1.3 is "older" than 1.21 (the way that versions are compared these days).

**Comment by dlaehnemann** [comment]
Also, the major executable (currently `sccaller_v1.2.py`) should probably be either updated to reflect the new version number or the version number removed, relying on git for the versioning, to avoid having to update the file name regularly?

**Comment by biosinodx** [comment]
Thank you epruesse and dlaehnemann for pointing out the confusion. The version should be called as 1.2.1. We are working on a major update to 1.3, in which we will significantly simply the current steps, minimize I/O, allow parallel processing, generate out put in VCF format and fix a few bugs. The 1.3 should be available at GitHub in about a month time.

**Comment by dlaehnemann** [comment]
Hi Xiao,

the renaming to `1.2.1` of the current version's release, as you suggested [over at bioconda](https://github.com/bioconda/bioconda-recipes/pull/11597#issuecomment-435468781) would do the trick, for now. If you could also rename the executable (either to `sccaller.py` to permanently stay that way, or to `sccaller_v1.2.1.py` to keep on counting the versions there, as well), that would in my opinion be the perfect solution.

cheers,
david

**Comment by epruesse** [comment]
@biosinodx Technically, with `1.21` already released, you should use `1.30` or `2.0` to get a version number larger than `1.21`. You could delete the tag and version for the `1.21` - if no-one added that to a collection of packages yet, it should be ok. If anyone did, it'll cause headache...

**Comment by biosinodx** [comment]
I see. I will use either 1.30 or 2.0 in the future.

Xiao

在 11/5/2018 1:15 PM, Elmar Pruesse 写道:

**Comment by dlaehnemann** [comment]
Thanks for the clarification! I'll then proceed with bioconda recipe update tomorrow, using version number and file name as is. All the best for the major updates you are working on!

**Comment by biosinodx** [comment]
Thank you David!

Xiao

在 11/7/2018 10:53 AM, David Laehnemann 写道:
