### ISSUE TITLE
NameError with script reasoning_v1.1.py

### ISSUE THREAD

**Issue by Goatofmountain** [biosinodx/SCcaller#6]
Hello !
I noticed that there is a name error on line 115 of python script reasoning_v1.1.py.
I think the file handle 'fileooute' should be amended to 'fileoout' to avoid the NameError in python. 

Thank you !

**Comment by biosinodx** [comment]
Hi, Thank you so much! We are finalizing a completely new version of sccaller. It will be shared in the github in one or two weeks.
