### ISSUE TITLE
What does "varreads" mean in the reason.txt file after run reasoning_v1.1.py?

### ISSUE THREAD

**Issue by shishimin** [biosinodx/SCcaller#8]
Hi,
there a lot of variants with 'varreads' in cell-bulk.reason.txt file, I want to know what does "varreads" mean in the reason.txt file after run reasoning_v1.1.py?

Thank you !

**Comment by biosinodx** [comment]
Hi, it means that there are reads reporting the same variant in the bulk bam file that you input to the reason_v1.1.py.

**Comment by biosinodx** [comment]
Btw, we are finalizing our new version of sccaller, in which we fixed some bugs in SNV/INDEL calling and made it much easier for users. You may see it here in the github after one or two weeks.
