### ISSUE TITLE
sccaller_v2.0.0.py: When choosing dbsnp, --bulk bulk_bamfile is required.

### ISSUE THREAD

**Issue by linkmonica** [biosinodx/SCcaller#9]
I get an error stating bulk bam is needed when using dbsnp, but if I had bulk bam, I would prefer using hsnp, the reason I am using dbsnp is due to absence of bulk bam.
Can you tell me a way out? or if anything wrong on my end?

Error: sccaller_v2.0.0.py: When choosing dbsnp, --bulk bulk_bamfile is required.

**Comment by biosinodx** [comment]
I see. This is a situation that we did not consider. Do you have bam 
files of multiple single cells of a same subject? If so, you can merge 
these bam together and use it as the bulk bam.

**Comment by linkmonica** [comment]
I will have a bulk bam soon, in the mean time I will take your idea of making a bulk bam, using sc bams. Thanks
